### ISSUE TITLE
Get rid of eval() call

### ISSUE THREAD

**Issue by zaverichintan** [phpmyadmin/motranslator#1]
Hey, 
Kindly help me, let me know how to get started ?

**Comment by nijel** [comment]
With what?

**Comment by zaverichintan** [comment]
I want to test in my local machine.

**Comment by nijel** [comment]
There is testsuite, so just download the sources and run it:

```
git clone https://github.com/nijel/motranslator.git
cd motranslator
composer update
./vendor/bin/phpunit -c phpunit.xml
```

**Comment by zaverichintan** [comment]
Thanx.
I was unable to find function alternative to eval .
And in php 7 eval error will not be able to catched.
So replacing eval is necessary now .

**Comment by nijel** [comment]
You can also use benchmark to check plurals performance if you make any changes:

```
php benchmark-plural.php
```

**Comment by zaverichintan** [comment]
Thanx. Is there any documentation there to understand codebase?

**Comment by nijel** [comment]
Not yet :-). But all interesting code is in src/MoTranslator.php

**Comment by zaverichintan** [comment]
I found this more useful for understanding plural forms http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

**Comment by nijel** [comment]
Well this is CLDR, for Gettext you might want to check https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html (for the background) or http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html (for equation examples).

**Comment by zaverichintan** [comment]
I am getting some idea about the code. I can help you with small changes and testing too. 
You might have to guide me.
