### ISSUE TITLE
Dummy _bind_textdomain_codeset implementation

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/motranslator#12]
The implementation of _bind_textdomain_codeset is:
```
/**
 * Dummy compatibility function, MoTranslator assumes
 * everything is UTF-8
 *
 * @return void
 */
function _bind_textdomain_codeset($domain, $codeset) {
    return;
}
```

in documentation (under Limitations):
>Input and output encoding has to match (preferably UTF-8)

fix:
	1. change the documentation (if non UTF-8 isn't supported) or change comment before _bind_textdomain_codeset function (assume input & output encoding are the same)
	2. throw exception (NotImplemented) in _bind_textdomain_codeset function if:
```
		strtolower($codeset) !== 'utf-8'
```

as the code will do nothing instead of changing codeset.

**Comment by nijel** [comment]
Anything works as long as input encoding is same as output one. As there is no way to figure out charset of the mo file, I'd rather do no assumptions about that here...
