### ISSUE TITLE
fpd on 32bit via negative result of unpack

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/motranslator#15]
unpack function on PHP that run in 32bit mode can return negative result as noted by the documentation: https://secure.php.net/manual/en/function.unpack.php#refsect1-function.unpack-notes

> Note that PHP internally stores integral values as signed. If you unpack a large unsigned long and it is of the same size as PHP internally stored values the result will be a negative number even though unsigned unpacking was specified.

thus can result in PHP Warning.
example: (run under PHP 32bit)
 ```
<?php
$negative32 = pack('CCCC', 0xFF, 0xFF, 0xFF, 0xFF);
file_put_contents('fpdle.mo',"\xde\x12\x04\x95".str_repeat($negative32,6));

include 'vendor/autoload.php';
$t=new PhpMyAdmin\MoTranslator\Translator('fpdle.mo');
print_r($t);
?>
```
result:
```
PHP Warning:  unpack(): Type V: not enough input, need 4, have 0 in /vendor/phpmyadmin/motranslator/src/StringReader.php on line 88
PHP Warning:  unpack(): Type V: not enough input, need 4, have 0 in /vendor/phpmyadmin/motranslator/src/StringReader.php on line 88
```

**Comment by nijel** [comment]
I currently don't have 32-bit system to test, so any feedback on fix is welcome.
