### ISSUE TITLE
Include twig support

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/motranslator#27]
Can you add the following files (from phpMyAdmin) to provide twig support:
- `Twig\I18nExtension`
- `Twig\I18n\TokenParserTrans`
- `Twig\I18n\NodeTrans`

In my local test this works perfectly (using my namespace)
```php
$twig->addExtension(new PhpMyAdmin\Twig\I18nExtension());
```

**Comment by nijel** [comment]
Probably makes sense to move it to the motranslator, what does @mauriciofauth think?

**Comment by williamdes** [comment]
@mauriciofauth ?


@nijel as I use the license `MPL-2.0` there is no problem in using `motranslator` as a dependency ?
See: [fossa](https://github.com/wdes/account-manager#license)
![selection_021](https://user-images.githubusercontent.com/7784660/40318805-2fc80dce-5d26-11e8-823f-cbcb99d861da.jpg)

**Comment by MauricioFauth** [comment]
@williamdes Is your idea to move these files to motranslator? With this, the motranslator would depend on `twig/extensions` and `twig/twig`.

**Comment by williamdes** [comment]
@mauriciofauth you are right

I see 4 solutions:
- Add dependency in the dev mode only
- Create a repository like `phpmyadmin/motranslator-twig`
- Add the files to this repository and use them without composer

**Comment by nijel** [comment]
Having separate repository sounds like a good choice, that way it will have correct deps and will be easier to integrate.

**Comment by MauricioFauth** [comment]
I agree with @nijel

**Comment by williamdes** [comment]
@nijel If you do not have time to create the repository I can create it and transfer ownership when you approve the contents of this new repository ?

**Comment by nijel** [comment]
It's now here https://github.com/phpmyadmin/motranslator-twig without any code

**Comment by williamdes** [comment]
Thank you !

By the way using https://github.com/phpstan/phpstan on my project showed me that:
> PhpMyAdmin\Twig\I18n\NodeTrans::__construct() does not call parent constructor from Twig_Extensions_Node_Trans.

I added :
```php
        parent::__construct($body, $plural, $count, $notes, $lineno, $tag);
```

If you use twig 2.x
> Return typehint of method PhpMyAdmin\Twig\I18n\TokenParserTrans::parse() has invalid type Twig_NodeInterface.

must be:
`
     * @return \Twig_Node
`
