### ISSUE TITLE
Bad usage of global functions.

### ISSUE THREAD

**Issue by ryanhowdy** [phpmyadmin/motranslator#44]
> Cannot redeclare __() (previously declared in /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:967

This package does not work with Laravel, and possible others because of the usage of global functions.

It would be great if you would wrap all the global functions in an `if (!function_exists())` call to ensure this does not happen.

**Comment by williamdes** [comment]
Thank you for reporting this @ryanhowdy !

**Comment by williamdes** [comment]
Fixed by #45
