### ISSUE TITLE
>= usage instead of > in read function

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/motranslator#8]
in read function:
```
if ($pos + $bytes >= $this->_len) {
            throw new ReaderException('Not enough bytes!');
        }
```
\>= should be replaced by > (there will be enough bytes if $pos + $bytes equal to $this->_len)

**Comment by zaverichintan** [comment]
IMHO - This is for Boundary condition and it does not change much of the efficiency of the program.
