### ISSUE TITLE
use single quotes instead of double quotes when possible

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/motranslator#9]
in preg_match call at:
https://github.com/phpmyadmin/motranslator/blob/master/src/Loader.php#L105
double quotes can be replaced by single quotes.

in other instances (array_push calls , $filename variable) it might be replaced (which improve performance) but will reduce legibility, more information:
https://stackoverflow.com/questions/3316060/single-quotes-or-double-quotes-for-variable-concatenation#3316126

**Comment by zaverichintan** [comment]
In the stackoverflow answer it says that - 

> However the added load in doing that is so small for the last versions of PHP that most of the time the conclusion is that it doesn't really matter.
> So for the performance people: use single quotes. For the "i like my code readable"-people: double quotes are a lot better for the legibility, as Flavius Stef already pointed out.

So performance boost is marginal but on the contrary $ sign changes performance. So will have to check exactly when the performance boost is effective.
